name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

on-run-end:
  - "{{ audit_failure_handler(results) }}"
  - "{{ dbt_logging(results) }}"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_new_project:
    # =====================================================================
    # SILVER LAYER (default DB + schema)
    # =====================================================================
    silver:
      +database: "{{ env_var('DBT_SILVER_DB', target.database) }}"
      # Default fallback schema (SILVER) added in environment variables
      +schema: "{{ env_var('DBT_SILVER_SCHEMA', target.schema) }}"
      +materialized: incremental

      # -------------------------------------------------------------
      # Seaware table routing to schema SEAWARE (SW1 + SW2 combined tables)
      # -------------------------------------------------------------
      seaware:
        +schema: "SEAWARE"
