{{
    config(
        materialized="incremental",
        incremental_strategy="merge",
        unique_key="TRANS_ID",
    )
}}
{% set last_updated_date = '1900-01-01 00:00:00' %}
with
    sw2_source as (
        select
            {{ Number_Transform('ACT_HIST_ID') }} as ACT_HIST_ID,
            {{ Number_Transform('AFTER_FPR_ID') }} as AFTER_FPR_ID,
            {{ Number_Transform('AMOUNT_FULL_BASE') }} as AMOUNT_FULL_BASE,
            {{ Number_Transform('AMOUNT_FULL_PRICE') }} as AMOUNT_FULL_PRICE,
            {{ Number_Transform('AMOUNT_FULL_TRANS') }} as AMOUNT_FULL_TRANS,
            {{ String_Transform('APPROVED_BY_USER_ID') }} as APPROVED_BY_USER_ID,
            {{ DateTime_Transform('APPROVED_TIME_STAMP') }} as APPROVED_TIME_STAMP,
            {{ DateTime_Transform('AR_AP_DUE_DATE') }} as AR_AP_DUE_DATE,
            {{ Number_Transform('AR_AP_SEQ_ID') }} as AR_AP_SEQ_ID,
            {{ DateTime_Transform('AR_AP_TIME_STAMP') }} as AR_AP_TIME_STAMP,
            {{ Number_Transform('BANK_FEE') }} as BANK_FEE,
            {{ Number_Transform('BANK_ID') }} as BANK_ID,
            {{ Number_Transform('BASE_ENTITY_ID') }} as BASE_ENTITY_ID,
            {{ String_Transform('BASE_ENTITY_TYPE') }} as BASE_ENTITY_TYPE,
            {{ Number_Transform('BATCH_HDR_ID') }} as BATCH_HDR_ID,
            {{ String_Transform('CC_AUTH_CODE') }} as CC_AUTH_CODE,
            {{ Number_Transform('CC_CLIENT_ID') }} as CC_CLIENT_ID,
            {{ String_Transform('CC_SERVER_TYPE') }} as CC_SERVER_TYPE,
            {{ String_Transform('COMMENTS') }} as COMMENTS,
            {{ Number_Transform('COMMISS_PAID') }} as COMMISS_PAID,
            {{ String_Transform('CURRENCY_PRICE') }} as CURRENCY_PRICE,
            {{ String_Transform('CURRENCY_TRANS') }} as CURRENCY_TRANS,
            {{ Number_Transform('DEST_ENTITY_ID') }} as DEST_ENTITY_ID,
            {{ String_Transform('DEST_ENTITY_TYPE') }} as DEST_ENTITY_TYPE,
            {{ String_Transform('DISTRIBUTION_CHANNEL') }} as DISTRIBUTION_CHANNEL,
            {{ DateTime_Transform('DUE_DATE') }} as DUE_DATE,
            {{ Number_Transform('EXCHANGE_GAIN') }} as EXCHANGE_GAIN,
            {{ String_Transform('EXCH_RATE_TYPE') }} as EXCH_RATE_TYPE,
            {{ String_Transform('EXTERNAL_IDENT') }} as EXTERNAL_IDENT,
            {{ String_Transform('FORM_OF_TRANS') }} as FORM_OF_TRANS,
            {{ Number_Transform('FPR_ID') }} as FPR_ID,
            {{ DateTime_Transform('GL_RATE_DATE') }} as GL_RATE_DATE,
            {{ String_Transform('GROSS_UP') }} as GROSS_UP,
            {{ String_Transform('GROUPING_LINE') }} as GROUPING_LINE,
            {{ String_Transform('INSUR_PAID') }} as INSUR_PAID,
            {{ String_Transform('INVOICED_SEPARATELY') }} as INVOICED_SEPARATELY,
            {{ String_Transform('IS_MANUAL') }} as IS_MANUAL,
            {{ DateTime_Transform('LAST_GL_DATE') }} as LAST_GL_DATE,
            {{ String_Transform('MERCHANT_NUMBER') }} as MERCHANT_NUMBER,
            {{ String_Transform('NOT_REFUNDABLE') }} as NOT_REFUNDABLE,
            {{ String_Transform('OFFICE_CODE') }} as OFFICE_CODE,
            {{ String_Transform('OFFICE_LOCATION') }} as OFFICE_LOCATION,
            {{ Number_Transform('PAYMENT_TRANS_ID') }} as PAYMENT_TRANS_ID,
            {{ Number_Transform('PMNT_FOR_CLIENT_ID') }} as PMNT_FOR_CLIENT_ID,
            {{ DateTime_Transform('POST_DATE') }} as POST_DATE,
            {{ Number_Transform('PREV_INVOICE_ID') }} as PREV_INVOICE_ID,
            {{ Number_Transform('RATE_PRICEBASE') }} as RATE_PRICEBASE,
            {{ Number_Transform('RATE_TRANSPRICE') }} as RATE_TRANSPRICE,
            {{ Number_Transform('SEC_TRANS_ID') }} as SEC_TRANS_ID,
            {{ String_Transform('SERVER_RESPONSE') }} as SERVER_RESPONSE,
            {{ String_Transform('SERVER_RESPONSE_LONG') }} as SERVER_RESPONSE_LONG,
            {{ String_Transform('SINGLE_INVOICED') }} as SINGLE_INVOICED,
            {{ Number_Transform('SOURCE_ENTITY_ID') }} as SOURCE_ENTITY_ID,
            {{ String_Transform('SOURCE_ENTITY_TYPE') }} as SOURCE_ENTITY_TYPE,
            {{ String_Transform('TERMS_CODE') }} as TERMS_CODE,
            {{ String_Transform('TO_BE_BALANCED') }} as TO_BE_BALANCED,
            {{ Number_Transform('TRANS_GROUP_ID') }} as TRANS_GROUP_ID,
            {{ String_Transform('TRANS_GUID') }} as TRANS_GUID,
            {{ Number_Transform('TRANS_ID') }} as TRANS_ID,
            {{ String_Transform('TRANS_LINK_TYPE') }} as TRANS_LINK_TYPE,
            {{ String_Transform('TRANS_STATUS') }} as TRANS_STATUS,
            {{ DateTime_Transform('TRANS_STATUS_TIME_STAMP') }} as TRANS_STATUS_TIME_STAMP,
            {{ DateTime_Transform('TRANS_TIME_STAMP') }} as TRANS_TIME_STAMP,
            {{ String_Transform('TRANS_TYPE') }} as TRANS_TYPE,
            {{ Number_Transform('USER_AGENT_ID') }} as USER_AGENT_ID,
            {{ Number_Transform('USER_CLIENT_ID') }} as USER_CLIENT_ID,
            {{ String_Transform('USER_ID') }} as USER_ID,
            {{ String_Transform('USER_TYPE') }} as USER_TYPE,
            {{ String_Transform('USE_EXTENDED_PAY') }} as USE_EXTENDED_PAY,
            {{ String_Transform('VOIDED_BY_USER_ID') }} as VOIDED_BY_USER_ID,
            {{ DateTime_Transform('VOIDED_TIME_STAMP') }} as VOIDED_TIME_STAMP,
            {{ Boolean_Transform('_FIVETRAN_DELETED') }} as _FIVETRAN_DELETED,
            {{ String_Transform('_FIVETRAN_ID') }} as _FIVETRAN_ID,
            {{ DateTime_Transform('_FIVETRAN_SYNCED') }} as _FIVETRAN_SYNCED,
            NULL as AMOUNT_ORIG_CURRENCY,
            NULL as AMOUNT_ORIG_CURRENCY_LEFT,
            NULL as CURRENCY_CODE,
            NULL as EXCHANGE_RATE,
            NULL as FIRST_TRANS_ID,
            NULL as INTERN_BALANCED_COM,
            NULL as PREV_TRANS_ID,
            NULL as REF_TRANS_ID,
            NULL as TRANS_AMOUNT,
            NULL as TRANS_AMOUNT_LEFT
    from {{ source('AMA_PROD_BRNZ_SW2','ACC_TRANS_DETAIL') }}
    ),
    sw1_source as (
        select
            {{ Number_Transform('ACT_HIST_ID') }} as ACT_HIST_ID,
            NULL as AFTER_FPR_ID,
            NULL as AMOUNT_FULL_BASE,
            NULL as AMOUNT_FULL_PRICE,
            NULL as AMOUNT_FULL_TRANS,
            {{ String_Transform('APPROVED_BY_USER_ID') }} as APPROVED_BY_USER_ID,
            {{ DateTime_Transform('APPROVED_TIME_STAMP') }} as APPROVED_TIME_STAMP,
            {{ DateTime_Transform('AR_AP_DUE_DATE') }} as AR_AP_DUE_DATE,
            {{ Number_Transform('AR_AP_SEQ_ID') }} as AR_AP_SEQ_ID,
            {{ DateTime_Transform('AR_AP_TIME_STAMP') }} as AR_AP_TIME_STAMP,
            NULL as BANK_FEE,
            NULL as BANK_ID,
            NULL as BASE_ENTITY_ID,
            NULL as BASE_ENTITY_TYPE,
            {{ Number_Transform('BATCH_HDR_ID') }} as BATCH_HDR_ID,
            {{ String_Transform('CC_AUTH_CODE') }} as CC_AUTH_CODE,
            {{ Number_Transform('CC_CLIENT_ID') }} as CC_CLIENT_ID,
            NULL as CC_SERVER_TYPE,
            {{ String_Transform('COMMENTS') }} as COMMENTS,
            NULL as COMMISS_PAID,
            NULL as CURRENCY_PRICE,
            NULL as CURRENCY_TRANS,
            {{ Number_Transform('DEST_ENTITY_ID') }} as DEST_ENTITY_ID,
            {{ String_Transform('DEST_ENTITY_TYPE') }} as DEST_ENTITY_TYPE,
            NULL as DISTRIBUTION_CHANNEL,
            {{ DateTime_Transform('DUE_DATE') }} as DUE_DATE,
            NULL as EXCHANGE_GAIN,
            {{ String_Transform('EXCH_RATE_TYPE') }} as EXCH_RATE_TYPE,
            {{ String_Transform('EXTERNAL_IDENT') }} as EXTERNAL_IDENT,
            {{ String_Transform('FORM_OF_TRANS') }} as FORM_OF_TRANS,
            {{ Number_Transform('FPR_ID') }} as FPR_ID,
            NULL as GL_RATE_DATE,
            NULL as GROSS_UP,
            NULL as GROUPING_LINE,
            {{ String_Transform('INSUR_PAID') }} as INSUR_PAID,
            NULL as INVOICED_SEPARATELY,
            {{ String_Transform('IS_MANUAL') }} as IS_MANUAL,
            NULL as LAST_GL_DATE,
            {{ String_Transform('MERCHANT_NUMBER') }} as MERCHANT_NUMBER,
            NULL as NOT_REFUNDABLE,
            {{ String_Transform('OFFICE_CODE') }} as OFFICE_CODE,
            {{ String_Transform('OFFICE_LOCATION') }} as OFFICE_LOCATION,
            NULL as PAYMENT_TRANS_ID,
            NULL as PMNT_FOR_CLIENT_ID,
            NULL as POST_DATE,
            NULL as PREV_INVOICE_ID,
            NULL as RATE_PRICEBASE,
            NULL as RATE_TRANSPRICE,
            NULL as SEC_TRANS_ID,
            NULL as SERVER_RESPONSE,
            NULL as SERVER_RESPONSE_LONG,
            NULL as SINGLE_INVOICED,
            {{ Number_Transform('SOURCE_ENTITY_ID') }} as SOURCE_ENTITY_ID,
            {{ String_Transform('SOURCE_ENTITY_TYPE') }} as SOURCE_ENTITY_TYPE,
            NULL as TERMS_CODE,
            NULL as TO_BE_BALANCED,
            {{ Number_Transform('TRANS_GROUP_ID') }} as TRANS_GROUP_ID,
            NULL as TRANS_GUID,
            {{ Number_Transform('TRANS_ID') }} as TRANS_ID,
            NULL as TRANS_LINK_TYPE,
            {{ String_Transform('TRANS_STATUS') }} as TRANS_STATUS,
            {{ DateTime_Transform('TRANS_STATUS_TIME_STAMP') }} as TRANS_STATUS_TIME_STAMP,
            {{ DateTime_Transform('TRANS_TIME_STAMP') }} as TRANS_TIME_STAMP,
            {{ String_Transform('TRANS_TYPE') }} as TRANS_TYPE,
            NULL as USER_AGENT_ID,
            NULL as USER_CLIENT_ID,
            {{ String_Transform('USER_ID') }} as USER_ID,
            NULL as USER_TYPE,
            {{ String_Transform('USE_EXTENDED_PAY') }} as USE_EXTENDED_PAY,
            {{ String_Transform('VOIDED_BY_USER_ID') }} as VOIDED_BY_USER_ID,
            {{ DateTime_Transform('VOIDED_TIME_STAMP') }} as VOIDED_TIME_STAMP,
            {{ Boolean_Transform('_FIVETRAN_DELETED') }} as _FIVETRAN_DELETED,
            NULL as _FIVETRAN_ID,
            {{ DateTime_Transform('_FIVETRAN_SYNCED') }} as _FIVETRAN_SYNCED,
            {{ Number_Transform('AMOUNT_ORIG_CURRENCY') }} as AMOUNT_ORIG_CURRENCY,
            {{ Number_Transform('AMOUNT_ORIG_CURRENCY_LEFT') }} as AMOUNT_ORIG_CURRENCY_LEFT,
            {{ String_Transform('CURRENCY_CODE') }} as CURRENCY_CODE,
            {{ Number_Transform('EXCHANGE_RATE') }} as EXCHANGE_RATE,
            {{ Number_Transform('FIRST_TRANS_ID') }} as FIRST_TRANS_ID,
            {{ String_Transform('INTERN_BALANCED_COM') }} as INTERN_BALANCED_COM,
            {{ Number_Transform('PREV_TRANS_ID') }} as PREV_TRANS_ID,
            {{ Number_Transform('REF_TRANS_ID') }} as REF_TRANS_ID,
            {{ Number_Transform('TRANS_AMOUNT') }} as TRANS_AMOUNT,
            {{ Number_Transform('TRANS_AMOUNT_LEFT') }} as TRANS_AMOUNT_LEFT
    from {{ source('AMA_PROD_BRNZ_SW1','ACC_TRANS_DETAIL') }}
    )
select *
from sw2_source
union all
select *
from sw1_source