{{
    config(
        materialized="incremental",
        incremental_strategy="merge",
        unique_key="TRANS_ID",
    )
}}
{% set last_updated_date = '1900-01-01 00:00:00' %}
with
    sw2_source as (
        select
            {{ transform_numeric(1,'ACT_HIST_ID') }} as ACT_HIST_ID,
            {{ transform_numeric(1,'AFTER_FPR_ID') }} as AFTER_FPR_ID,
            {{ transform_numeric(1,'AMOUNT_FULL_BASE') }} as AMOUNT_FULL_BASE,
            {{ transform_numeric(1,'AMOUNT_FULL_PRICE') }} as AMOUNT_FULL_PRICE,
            {{ transform_numeric(1,'AMOUNT_FULL_TRANS') }} as AMOUNT_FULL_TRANS,
            {{ transform_string(1,'APPROVED_BY_USER_ID') }} as APPROVED_BY_USER_ID,
            {{ transform_datetime(1,'APPROVED_TIME_STAMP') }} as APPROVED_TIME_STAMP,
            {{ transform_datetime(1,'AR_AP_DUE_DATE') }} as AR_AP_DUE_DATE,
            {{ transform_numeric(1,'AR_AP_SEQ_ID') }} as AR_AP_SEQ_ID,
            {{ transform_datetime(1,'AR_AP_TIME_STAMP') }} as AR_AP_TIME_STAMP,
            {{ transform_numeric(1,'BANK_FEE') }} as BANK_FEE,
            {{ transform_numeric(1,'BANK_ID') }} as BANK_ID,
            {{ transform_numeric(1,'BASE_ENTITY_ID') }} as BASE_ENTITY_ID,
            {{ transform_string(1,'BASE_ENTITY_TYPE') }} as BASE_ENTITY_TYPE,
            {{ transform_numeric(1,'BATCH_HDR_ID') }} as BATCH_HDR_ID,
            {{ transform_string(1,'CC_AUTH_CODE') }} as CC_AUTH_CODE,
            {{ transform_numeric(1,'CC_CLIENT_ID') }} as CC_CLIENT_ID,
            {{ transform_string(1,'CC_SERVER_TYPE') }} as CC_SERVER_TYPE,
            {{ transform_string(1,'COMMENTS') }} as COMMENTS,
            {{ transform_numeric(1,'COMMISS_PAID') }} as COMMISS_PAID,
            {{ transform_string(1,'CURRENCY_PRICE') }} as CURRENCY_PRICE,
            {{ transform_string(1,'CURRENCY_TRANS') }} as CURRENCY_TRANS,
            {{ transform_numeric(1,'DEST_ENTITY_ID') }} as DEST_ENTITY_ID,
            {{ transform_string(1,'DEST_ENTITY_TYPE') }} as DEST_ENTITY_TYPE,
            {{ transform_string(1,'DISTRIBUTION_CHANNEL') }} as DISTRIBUTION_CHANNEL,
            {{ transform_datetime(1,'DUE_DATE') }} as DUE_DATE,
            {{ transform_numeric(1,'EXCHANGE_GAIN') }} as EXCHANGE_GAIN,
            {{ transform_string(1,'EXCH_RATE_TYPE') }} as EXCH_RATE_TYPE,
            {{ transform_string(1,'EXTERNAL_IDENT') }} as EXTERNAL_IDENT,
            {{ transform_string(1,'FORM_OF_TRANS') }} as FORM_OF_TRANS,
            {{ transform_numeric(1,'FPR_ID') }} as FPR_ID,
            {{ transform_datetime(1,'GL_RATE_DATE') }} as GL_RATE_DATE,
            {{ transform_string(1,'GROSS_UP') }} as GROSS_UP,
            {{ transform_string(1,'GROUPING_LINE') }} as GROUPING_LINE,
            {{ transform_string(1,'INSUR_PAID') }} as INSUR_PAID,
            {{ transform_string(1,'INVOICED_SEPARATELY') }} as INVOICED_SEPARATELY,
            {{ transform_string(1,'IS_MANUAL') }} as IS_MANUAL,
            {{ transform_datetime(1,'LAST_GL_DATE') }} as LAST_GL_DATE,
            {{ transform_string(1,'MERCHANT_NUMBER') }} as MERCHANT_NUMBER,
            {{ transform_string(1,'NOT_REFUNDABLE') }} as NOT_REFUNDABLE,
            {{ transform_string(1,'OFFICE_CODE') }} as OFFICE_CODE,
            {{ transform_string(1,'OFFICE_LOCATION') }} as OFFICE_LOCATION,
            {{ transform_numeric(1,'PAYMENT_TRANS_ID') }} as PAYMENT_TRANS_ID,
            {{ transform_numeric(1,'PMNT_FOR_CLIENT_ID') }} as PMNT_FOR_CLIENT_ID,
            {{ transform_datetime(1,'POST_DATE') }} as POST_DATE,
            {{ transform_numeric(1,'PREV_INVOICE_ID') }} as PREV_INVOICE_ID,
            {{ transform_numeric(1,'RATE_PRICEBASE') }} as RATE_PRICEBASE,
            {{ transform_numeric(1,'RATE_TRANSPRICE') }} as RATE_TRANSPRICE,
            {{ transform_numeric(1,'SEC_TRANS_ID') }} as SEC_TRANS_ID,
            {{ transform_string(1,'SERVER_RESPONSE') }} as SERVER_RESPONSE,
            {{ transform_string(1,'SERVER_RESPONSE_LONG') }} as SERVER_RESPONSE_LONG,
            {{ transform_string(1,'SINGLE_INVOICED') }} as SINGLE_INVOICED,
            {{ transform_numeric(1,'SOURCE_ENTITY_ID') }} as SOURCE_ENTITY_ID,
            {{ transform_string(1,'SOURCE_ENTITY_TYPE') }} as SOURCE_ENTITY_TYPE,
            {{ transform_string(1,'TERMS_CODE') }} as TERMS_CODE,
            {{ transform_string(1,'TO_BE_BALANCED') }} as TO_BE_BALANCED,
            {{ transform_numeric(1,'TRANS_GROUP_ID') }} as TRANS_GROUP_ID,
            {{ transform_string(1,'TRANS_GUID') }} as TRANS_GUID,
            {{ transform_numeric(1,'TRANS_ID') }} as TRANS_ID,
            {{ transform_string(1,'TRANS_LINK_TYPE') }} as TRANS_LINK_TYPE,
            {{ transform_string(1,'TRANS_STATUS') }} as TRANS_STATUS,
            {{ transform_datetime(1,'TRANS_STATUS_TIME_STAMP') }} as TRANS_STATUS_TIME_STAMP,
            {{ transform_datetime(1,'TRANS_TIME_STAMP') }} as TRANS_TIME_STAMP,
            {{ transform_string(1,'TRANS_TYPE') }} as TRANS_TYPE,
            {{ transform_numeric(1,'USER_AGENT_ID') }} as USER_AGENT_ID,
            {{ transform_numeric(1,'USER_CLIENT_ID') }} as USER_CLIENT_ID,
            {{ transform_string(1,'USER_ID') }} as USER_ID,
            {{ transform_string(1,'USER_TYPE') }} as USER_TYPE,
            {{ transform_string(1,'USE_EXTENDED_PAY') }} as USE_EXTENDED_PAY,
            {{ transform_string(1,'VOIDED_BY_USER_ID') }} as VOIDED_BY_USER_ID,
            {{ transform_datetime(1,'VOIDED_TIME_STAMP') }} as VOIDED_TIME_STAMP,
            _FIVETRAN_DELETED,
            {{ transform_string(1,'_FIVETRAN_ID') }} as _FIVETRAN_ID,
            {{ transform_datetime(1,'_FIVETRAN_SYNCED') }} as _FIVETRAN_SYNCED,
            NULL as AMOUNT_ORIG_CURRENCY,
            NULL as AMOUNT_ORIG_CURRENCY_LEFT,
            NULL as CURRENCY_CODE,
            NULL as EXCHANGE_RATE,
            NULL as FIRST_TRANS_ID,
            NULL as INTERN_BALANCED_COM,
            NULL as PREV_TRANS_ID,
            NULL as REF_TRANS_ID,
            NULL as TRANS_AMOUNT,
            NULL as TRANS_AMOUNT_LEFT
    from {{ source('AMA_PROD_BRNZ_SW2','ACC_TRANS_DETAIL') }}
    ),
    sw1_source as (
        select
            {{ transform_numeric(1,'ACT_HIST_ID') }} as ACT_HIST_ID,
            NULL as AFTER_FPR_ID,
            NULL as AMOUNT_FULL_BASE,
            NULL as AMOUNT_FULL_PRICE,
            NULL as AMOUNT_FULL_TRANS,
            {{ transform_string(1,'APPROVED_BY_USER_ID') }} as APPROVED_BY_USER_ID,
            {{ transform_datetime(1,'APPROVED_TIME_STAMP') }} as APPROVED_TIME_STAMP,
            {{ transform_datetime(1,'AR_AP_DUE_DATE') }} as AR_AP_DUE_DATE,
            {{ transform_numeric(1,'AR_AP_SEQ_ID') }} as AR_AP_SEQ_ID,
            {{ transform_datetime(1,'AR_AP_TIME_STAMP') }} as AR_AP_TIME_STAMP,
            NULL as BANK_FEE,
            NULL as BANK_ID,
            NULL as BASE_ENTITY_ID,
            NULL as BASE_ENTITY_TYPE,
            {{ transform_numeric(1,'BATCH_HDR_ID') }} as BATCH_HDR_ID,
            {{ transform_string(1,'CC_AUTH_CODE') }} as CC_AUTH_CODE,
            {{ transform_numeric(1,'CC_CLIENT_ID') }} as CC_CLIENT_ID,
            NULL as CC_SERVER_TYPE,
            {{ transform_string(1,'COMMENTS') }} as COMMENTS,
            NULL as COMMISS_PAID,
            NULL as CURRENCY_PRICE,
            NULL as CURRENCY_TRANS,
            {{ transform_numeric(1,'DEST_ENTITY_ID') }} as DEST_ENTITY_ID,
            {{ transform_string(1,'DEST_ENTITY_TYPE') }} as DEST_ENTITY_TYPE,
            NULL as DISTRIBUTION_CHANNEL,
            {{ transform_datetime(1,'DUE_DATE') }} as DUE_DATE,
            NULL as EXCHANGE_GAIN,
            {{ transform_string(1,'EXCH_RATE_TYPE') }} as EXCH_RATE_TYPE,
            {{ transform_string(1,'EXTERNAL_IDENT') }} as EXTERNAL_IDENT,
            {{ transform_string(1,'FORM_OF_TRANS') }} as FORM_OF_TRANS,
            {{ transform_numeric(1,'FPR_ID') }} as FPR_ID,
            NULL as GL_RATE_DATE,
            NULL as GROSS_UP,
            NULL as GROUPING_LINE,
            {{ transform_string(1,'INSUR_PAID') }} as INSUR_PAID,
            NULL as INVOICED_SEPARATELY,
            {{ transform_string(1,'IS_MANUAL') }} as IS_MANUAL,
            NULL as LAST_GL_DATE,
            {{ transform_string(1,'MERCHANT_NUMBER') }} as MERCHANT_NUMBER,
            NULL as NOT_REFUNDABLE,
            {{ transform_string(1,'OFFICE_CODE') }} as OFFICE_CODE,
            {{ transform_string(1,'OFFICE_LOCATION') }} as OFFICE_LOCATION,
            NULL as PAYMENT_TRANS_ID,
            NULL as PMNT_FOR_CLIENT_ID,
            NULL as POST_DATE,
            NULL as PREV_INVOICE_ID,
            NULL as RATE_PRICEBASE,
            NULL as RATE_TRANSPRICE,
            NULL as SEC_TRANS_ID,
            NULL as SERVER_RESPONSE,
            NULL as SERVER_RESPONSE_LONG,
            NULL as SINGLE_INVOICED,
            {{ transform_numeric(1,'SOURCE_ENTITY_ID') }} as SOURCE_ENTITY_ID,
            {{ transform_string(1,'SOURCE_ENTITY_TYPE') }} as SOURCE_ENTITY_TYPE,
            NULL as TERMS_CODE,
            NULL as TO_BE_BALANCED,
            {{ transform_numeric(1,'TRANS_GROUP_ID') }} as TRANS_GROUP_ID,
            NULL as TRANS_GUID,
            {{ transform_numeric(1,'TRANS_ID') }} as TRANS_ID,
            NULL as TRANS_LINK_TYPE,
            {{ transform_string(1,'TRANS_STATUS') }} as TRANS_STATUS,
            {{ transform_datetime(1,'TRANS_STATUS_TIME_STAMP') }} as TRANS_STATUS_TIME_STAMP,
            {{ transform_datetime(1,'TRANS_TIME_STAMP') }} as TRANS_TIME_STAMP,
            {{ transform_string(1,'TRANS_TYPE') }} as TRANS_TYPE,
            NULL as USER_AGENT_ID,
            NULL as USER_CLIENT_ID,
            {{ transform_string(1,'USER_ID') }} as USER_ID,
            NULL as USER_TYPE,
            {{ transform_string(1,'USE_EXTENDED_PAY') }} as USE_EXTENDED_PAY,
            {{ transform_string(1,'VOIDED_BY_USER_ID') }} as VOIDED_BY_USER_ID,
            {{ transform_datetime(1,'VOIDED_TIME_STAMP') }} as VOIDED_TIME_STAMP,
            _FIVETRAN_DELETED,
            NULL as _FIVETRAN_ID,
            {{ transform_datetime(1,'_FIVETRAN_SYNCED') }} as _FIVETRAN_SYNCED,
            {{ transform_numeric(1,'AMOUNT_ORIG_CURRENCY') }} as AMOUNT_ORIG_CURRENCY,
            {{ transform_numeric(1,'AMOUNT_ORIG_CURRENCY_LEFT') }} as AMOUNT_ORIG_CURRENCY_LEFT,
            {{ transform_string(1,'CURRENCY_CODE') }} as CURRENCY_CODE,
            {{ transform_numeric(1,'EXCHANGE_RATE') }} as EXCHANGE_RATE,
            {{ transform_numeric(1,'FIRST_TRANS_ID') }} as FIRST_TRANS_ID,
            {{ transform_string(1,'INTERN_BALANCED_COM') }} as INTERN_BALANCED_COM,
            {{ transform_numeric(1,'PREV_TRANS_ID') }} as PREV_TRANS_ID,
            {{ transform_numeric(1,'REF_TRANS_ID') }} as REF_TRANS_ID,
            {{ transform_numeric(1,'TRANS_AMOUNT') }} as TRANS_AMOUNT,
            {{ transform_numeric(1,'TRANS_AMOUNT_LEFT') }} as TRANS_AMOUNT_LEFT
    from {{ source('AMA_PROD_BRNZ_SW1','ACC_TRANS_DETAIL')}}
    )
select *
from sw2_source
union all
select *
from sw1_source