version: 2

sources:
  - name: SW1
    database: AMA_PROD_BRNZ
    schema: SW1_SEAWARE
    description: "Source tables from the SW1 Seaware application"
    tables:

      - name: RES_INVOICE_ITEM
      - name: RES_HEADER
      - name: AGENCY
      - name: SAIL_HEADER
      - name: SHIP
      - name: ACC_TRANS_DETAIL
      - name: PACKAGE_DEFINITION
      - name: RES_GUEST
      - name: CLIENT
      - name: VCS_ADDITIONAL_FIELD_VALUE
      - name: RES_COMMISSION_DETAIL
      - name: RES_PROMOTION
      - name: PACKAGE_TYPE
      - name: AGENCY_HierarchyChain
      - name: AGENCY_HierarchyConsortium
      - name: AGENCY_CLASSIFICATION
      - name: INVOICE_ITEM_GROUP
      - name: INV_ITEM_GROUP_MATCH
      - name: RES_PACKAGE
      - name: RES_AIR_REQUEST
      - name: RES_AIR_TICKETS
      - name: AIR_REQ_ITIN
      - name: AM_ORDER_HEADER
      - name: AM_ORDER_ITEM
      - name: RES_ADDON
      - name: AM_CODE
      - name: RES_PACKAGE_COUPON
      - name: ACC_COUPON
      - name: REGION_CONTACT
      - name: REGION
      - name: USER_LOGIN
      - name: RES_HIST_TRANS
      - name: RES_HIST_VALUE
      - name: RES_HIST_TREE
      - name: AGENT
      - name: RES_CHARGE_DETAIL
      - name: CABIN_INVENTORY
      - name: RV_GROUP_INFO
      - name: RES_WTL_REQUEST
      - name: COND_STR_LIB
      - name: RES_HEADER_CounponIssued
      - name: SAIL_HEADER_CouponIssued
      - name: RES_PACKAGECOUPON
      - name: RES_HEADER_CouponUsed
      - name: SAIL_HEADER_CouponUsed
      - name: RES_GUEST_CouponUsed
      - name: SAIL_HEADER_CouponUsedPmt
      - name: RES_HEADER_CouponUsedPmt
      - name: AGENCY_ADDRESS
      - name: COUNTRY
      - name: GROUP_BOOKING
      - name: GROUP_COMMISSION_DETAIL
      - name: GROUP_INVOICE_ITEM
      - name: GROUP_PAY_DUE_ITEM
      - name: GROUP_PROMOTION
      - name: GROUP_SHIP_REQUEST
      - name: GROUP_TYPE
      - name: PAP_MASTER
      - name: PORT
      - name: SHIP_INVENTORY_ALLOC
      - name: TOUR_CREDIT
      - name: ACC_TRANS_TYPE
      - name: AGENCY_CLASSIFICATION_LINK
      - name: AGENCY_PHONE
      - name: AGENCY_REGION_LINK
      - name: AGENT_ADDRESS
      - name: AGENT_REGION_LINK
      - name: AM_INVOICE_ITEM
      - name: CURRENCY_EXCHNG_RATE
      - name: HOUSEHOLD_ADDRESS
      - name: REGION_DISTRICT_LINK
      - name: RES_CHARGE_COMMISSION
      - name: RES_CHARGE_SUBDETAIL
      - name: RES_COMPONENT
      - name: RES_EVENT
      - name: RES_GUEST_PARAM
      - name: RES_HOTEL_REQUEST
      - name: RES_PARAM
      - name: RES_PROTECTED_COMMISSION
      - name: RES_SHIP_REQUEST
      - name: SAIL_ACTIVITY
      - name: SAIL_EVENT_TYPE
      - name: SHIP_CABIN_CTG_LINK
      - name: AGENCY_CONTACT
      - name: AGENT_PHONE
      - name: SHIP_CABIN
      - name: SHIP_CABIN_RESERVE
      - name: HOUSEHOLD_PHONE
      - name: AGENCY_LINK
      - name: ACC_COUPON_CLASS
      - name: CC_CLIENT
      - name: RES_ARCHIVE
      - name: RES_ARCHIVE_CLNT_LNK
      - name: SP_REQ_CODE
      - name: SP_REQ_ORDER
      - name: SP_REQ_ORD_ITEM
      - name: TW_RES_DETAIL
      - name: TW_RES_HEADER
      - name: AIRLINE
      - name: AIRPORT
      - name: RES_AIR_REQUEST_SEGMENT
      - name: CITY
      - name: GROUP_HOTEL_REQUEST
      - name: GROUP_LAND_PACKAGE
      - name: HOTEL
      - name: PACKAGE_ITINERARY
      - name: SUGGESTED_LAND_PACKAGE
      - name: RES_INVOICE_CANC
      - name: VCS_LOG_FIELD
      - name: VCS_LOG_RECORD
      - name: RES_PAYMENT_DUE_ITEM
      - name: COLLAT_ALT_ADDR
      - name: COLLAT_ORDER
      - name: COLLAT_ORDER_ITEMS
      - name: ACC_INVOICE_DETAIL
      - name: SEAWARE_SETTINGS
      - name: TOUR_CREDIT_DISTRIBUTION
      - name: HOTEL_INV_ALLOCATION
      - name: RES_GUEST_IN_ROOM
      - name: HOTEL_CATEGORY_ASSIGN
      - name: HOTEL_CITY_LINK
      - name: HOTEL_INVENTORY
      - name: HOTEL_INV_ASSIGN
      - name: GTB_DOC_QUEUE
      - name: GTB_REQUEST
      - name: SW_DOCUMENTS
      - name: ACC_BATCH_HEADER
      - name: ACC_FORM_OF_TRANS
      - name: ACC_REFUND_TRANS
      - name: AGENCY_COMMISSION
      - name: AGENCY_COMMUNICATION
      - name: AGENCY_EXTERNAL
      - name: CABIN_ATTRIBUTE
      - name: CABIN_ATTRIBUTE_LINK
      - name: CABIN_CATEGORY
      - name: CABIN_CATEGORY_COMMENTS
      - name: CABIN_CATEGORY_GENERIC
      - name: CABIN_LAYOUT
      - name: CLIENT_PROGRAM
      - name: CLIENT_SPECIAL_DATE
      - name: COMMISSION_CODE
      - name: COMPONENT_TYPE
      - name: DISTRICT_TYPE
      - name: EXTERNAL_NAMES
      - name: GROUP_EVENT
      - name: GROUP_USER_NOTES
      - name: GTB_DOC_HISTORY
      - name: GTB_REQUEST_HISTORY
      - name: GUEST_TYPE
      - name: HOTEL_ADDRESS
      - name: HOTEL_PHONE
      - name: HOUSEHOLD
      - name: INSUR_EXCH_LOG_DETAIL
      - name: INSUR_EXCH_LOG_HEADER
      - name: INSUR_EXCH_STATUS
      - name: INSURANCE_EXCH_HEADER
      - name: INSURANCE_TYPE
      - name: PACKAGE_CLASS_CODE
      - name: PACKAGE_CLASS_LINK
      - name: PACKAGE_CLASS_TYPE
      - name: PACKAGE_COLOR
      - name: PACKAGE_ITIN_OPTION
      - name: PACKAGE_ITIN_PACKAGE_LINK
      - name: PACKAGE_SELLING_LIMIT
      - name: PACKAGE_SELLING_USAGE
      - name: PAP_EXTERNAL
      - name: PAP_TYPE
      - name: PHONE_TYPE
      - name: PORT_PIER
      - name: RES_CHARGEABLE_ACTION
      - name: RES_EVENT_TYPE
      - name: RES_NOTES_HISTORY
      - name: RES_PMNT_SCH_REQ
      - name: RES_ROOM_REQUEST
      - name: RES_UPDATE_BATCH_HEADER
      - name: SHIP_DECK
      - name: USER_NOTE_SUBJECT
      - name: VCS_DOMAIN_LIST_VALUE
      - name: VCS_ROW_TYPE
      - name: VCS_TYPE_FIELD
      - name: VENDOR
      - name: VENDOR_PHONE
      - name: VENDOR_PKG_ASSIGNMENT

  - name: SW2
    database: AMA_PROD_BRNZ
    schema: SW2_SEAWARE
    description: "Source tables from the SW2 Seaware application"
    tables:

      - name: RES_INVOICE_ITEM
      - name: RES_HEADER
      - name: AGENCY
      - name: SAIL_HEADER
      - name: SHIP
      - name: ACC_TRANS_DETAIL
      - name: PACKAGE_DEFINITION
      - name: RES_GUEST
      - name: CLIENT
      - name: VCS_ADDITIONAL_FIELD_VALUE
      - name: RES_COMMISSION_DETAIL
      - name: RES_PROMOTION
      - name: PACKAGE_TYPE
      - name: AGENCY_HierarchyChain
      - name: AGENCY_HierarchyConsortium
      - name: AGENCY_CLASSIFICATION
      - name: INVOICE_ITEM_GROUP
      - name: INV_ITEM_GROUP_MATCH
      - name: RES_PACKAGE
      - name: RES_AIR_REQUEST
      - name: RES_AIR_TICKETS
      - name: AIR_REQ_ITIN
      - name: AM_ORDER_HEADER
      - name: AM_ORDER_ITEM
      - name: RES_ADDON
      - name: AM_CODE
      - name: RES_PACKAGE_COUPON
      - name: ACC_COUPON
      - name: REGION_CONTACT
      - name: REGION
      - name: USER_LOGIN
      - name: RES_HIST_TRANS
      - name: RES_HIST_VALUE
      - name: RES_HIST_TREE
      - name: AGENT
      - name: RES_CHARGE_DETAIL
      - name: CABIN_INVENTORY
      - name: RV_GROUP_INFO
      - name: RES_WTL_REQUEST
      - name: COND_STR_LIB
      - name: RES_HEADER_CounponIssued
      - name: SAIL_HEADER_CouponIssued
      - name: RES_PACKAGECOUPON
      - name: RES_HEADER_CouponUsed
      - name: SAIL_HEADER_CouponUsed
      - name: RES_GUEST_CouponUsed
      - name: SAIL_HEADER_CouponUsedPmt
      - name: RES_HEADER_CouponUsedPmt
      - name: AGENCY_ADDRESS
      - name: COUNTRY
      - name: GROUP_BOOKING
      - name: GROUP_COMMISSION_DETAIL
      - name: GROUP_INVOICE_ITEM
      - name: GROUP_PAY_DUE_ITEM
      - name: GROUP_PROMOTION
      - name: GROUP_SHIP_REQUEST
      - name: GROUP_TYPE
      - name: PAP_MASTER
      - name: PORT
      - name: SHIP_INVENTORY_ALLOC
      - name: TOUR_CREDIT
      - name: ACC_TRANS_TYPE
      - name: AGENCY_CLASSIFICATION_LINK
      - name: AGENCY_PHONE
      - name: AGENCY_REGION_LINK
      - name: AGENT_ADDRESS
      - name: AGENT_REGION_LINK
      - name: AM_INVOICE_ITEM
      - name: CURRENCY_EXCHNG_RATE
      - name: HOUSEHOLD_ADDRESS
      - name: REGION_DISTRICT_LINK
      - name: RES_CHARGE_COMMISSION
      - name: RES_CHARGE_SUBDETAIL
      - name: RES_COMPONENT
      - name: RES_EVENT
      - name: RES_GUEST_PARAM
      - name: RES_HOTEL_REQUEST
      - name: RES_PARAM
      - name: RES_PROTECTED_COMMISSION
      - name: RES_SHIP_REQUEST
      - name: SAIL_ACTIVITY
      - name: SAIL_EVENT_TYPE
      - name: SHIP_CABIN_CTG_LINK
      - name: AGENCY_CONTACT
      - name: AGENT_PHONE
      - name: SHIP_CABIN
      - name: SHIP_CABIN_RESERVE
      - name: HOUSEHOLD_PHONE
      - name: AGENCY_LINK
      - name: ACC_COUPON_CLASS
      - name: CC_CLIENT
      - name: RES_ARCHIVE
      - name: RES_ARCHIVE_CLNT_LNK
      - name: SP_REQ_CODE
      - name: SP_REQ_ORDER
      - name: SP_REQ_ORD_ITEM
      - name: TW_RES_DETAIL
      - name: TW_RES_HEADER
      - name: AIRLINE
      - name: AIRPORT
      - name: RES_AIR_REQUEST_SEGMENT
      - name: CITY
      - name: GROUP_HOTEL_REQUEST
      - name: GROUP_LAND_PACKAGE
      - name: HOTEL
      - name: PACKAGE_ITINERARY
      - name: SUGGESTED_LAND_PACKAGE
      - name: RES_INVOICE_CANC
      - name: VCS_LOG_FIELD
      - name: VCS_LOG_RECORD
      - name: RES_PAYMENT_DUE_ITEM
      - name: COLLAT_ALT_ADDR
      - name: COLLAT_ORDER
      - name: COLLAT_ORDER_ITEMS
      - name: ACC_INVOICE_DETAIL
      - name: SEAWARE_SETTINGS
      - name: TOUR_CREDIT_DISTRIBUTION
      - name: HOTEL_INV_ALLOCATION
      - name: RES_GUEST_IN_ROOM
      - name: HOTEL_CATEGORY_ASSIGN
      - name: HOTEL_CITY_LINK
      - name: HOTEL_INVENTORY
      - name: HOTEL_INV_ASSIGN
      - name: GTB_DOC_QUEUE
      - name: GTB_REQUEST
      - name: SW_DOCUMENTS
      - name: ACC_BATCH_HEADER
      - name: ACC_FORM_OF_TRANS
      - name: ACC_REFUND_TRANS
      - name: AGENCY_COMMISSION
      - name: AGENCY_COMMUNICATION
      - name: AGENCY_EXTERNAL
      - name: CABIN_ATTRIBUTE
      - name: CABIN_ATTRIBUTE_LINK
      - name: CABIN_CATEGORY
      - name: CABIN_CATEGORY_COMMENTS
      - name: CABIN_CATEGORY_GENERIC
      - name: CABIN_LAYOUT
      - name: CLIENT_PROGRAM
      - name: CLIENT_SPECIAL_DATE
      - name: COMMISSION_CODE
      - name: COMPONENT_TYPE
      - name: DISTRICT_TYPE
      - name: EXTERNAL_NAMES
      - name: GROUP_EVENT
      - name: GROUP_USER_NOTES
      - name: GTB_DOC_HISTORY
      - name: GTB_REQUEST_HISTORY
      - name: GUEST_TYPE
      - name: HOTEL_ADDRESS
      - name: HOTEL_PHONE
      - name: HOUSEHOLD
      - name: INSUR_EXCH_LOG_DETAIL
      - name: INSUR_EXCH_LOG_HEADER
      - name: INSUR_EXCH_STATUS
      - name: INSURANCE_EXCH_HEADER
      - name: INSURANCE_TYPE
      - name: PACKAGE_CLASS_CODE
      - name: PACKAGE_CLASS_LINK
      - name: PACKAGE_CLASS_TYPE
      - name: PACKAGE_COLOR
      - name: PACKAGE_ITIN_OPTION
      - name: PACKAGE_ITIN_PACKAGE_LINK
      - name: PACKAGE_SELLING_LIMIT
      - name: PACKAGE_SELLING_USAGE
      - name: PAP_EXTERNAL
      - name: PAP_TYPE
      - name: PHONE_TYPE
      - name: PORT_PIER
      - name: RES_CHARGEABLE_ACTION
      - name: RES_EVENT_TYPE
      - name: RES_NOTES_HISTORY
      - name: RES_PMNT_SCH_REQ
      - name: RES_ROOM_REQUEST
      - name: RES_UPDATE_BATCH_HEADER
      - name: SHIP_DECK
      - name: USER_NOTE_SUBJECT
      - name: VCS_DOMAIN_LIST_VALUE
      - name: VCS_ROW_TYPE
      - name: VCS_TYPE_FIELD
      - name: VENDOR
      - name: VENDOR_PHONE
      - name: VENDOR_PKG_ASSIGNMENT

